/*
 * Project name:
     Client_UI.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     25-05-2012
 * Time of creation
     20:27:37
 * Test configuration:
     MCU:             LM3S9B95
     Dev.Board:       EasyMx_PRO_v7_for_Stellaris_ARM
                      http://www.mikroe.com/eng/products/view/792/easymx-pro-v7-for-stellaris-arm/
     Oscillator:      80000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/eng/products/view/752/mikroc-pro-for-arm/
 */

#include "Client_UI_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();

  }

}
